version: '3.8'
services:
  backend-api:
    container_name: backend-assets
    image: ghcr.io/paulords95/binance-asset-history/assets-binance:latest
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - '127.0.0.1:5433:5432'
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
